### ISSUE TITLE
linux arm64 build failed!

### ISSUE THREAD

**Issue by toplinuxsir** [sony/flutter-embedded-linux#328] opened 2023-02-10 01:03 UTC
error as below
```
Compilation to SkSL failed.
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: GLSL to SPIRV failed;
Compilation error. 3 error(s) and 1 warning(s).
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: warning: (version, profile)
forced to be (460, core), while in source code it is (320, es)
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:9: error: '#include' : Included
file not found. for header name: flutter/runtime_effect.glsl
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: 'FlutterFragCoord' :
no matching overloaded function found
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: '=' :  cannot convert
from ' const float' to ' temp 2-component vector of float'




ShaderCompilerException: Shader compilation of
"/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag" to
"/home/orangepi/devs/poscommit_win/build/elinux/flutter_assets/shaders/ink_sparkle.frag" failed with exit code 1.
impellerc stdout:

impellerc stderr:
Compilation to SkSL failed.
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: GLSL to SPIRV failed;
Compilation error. 3 error(s) and 1 warning(s).
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: warning: (version, profile)
forced to be (460, core), while in source code it is (320, es)
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:9: error: '#include' : Included
file not found. for header name: flutter/runtime_effect.glsl
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: 'FlutterFragCoord' :
no matching overloaded function found
/opt/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: '=' :  cannot convert
from ' const float' to ' temp 2-component vector of float'





```

**Comment by HidenoriMatsubayashi** [comment] 2023-02-10 01:34
Closing as this is a duplicate of https://github.com/sony/flutter-elinux/issues/161

**Closed by HidenoriMatsubayashi** 2023-02-10 01:34 UTC
Labels: duplicate
